apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: gremlin
  namespace: kube-system
  labels:
    k8s-app: gremlin
    version: v1
spec:
  template:
    metadata:
      labels:
        name: gremlin
        k8s-app: gremlin
        version: v1
    spec:
      containers:
      - name: gremlin
        image: gremlin/gremlin
        args: [ "daemon" ]
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_BOOT
              - SYS_TIME
              - KILL
        env:
          - name: GREMLIN_ORG_ID
            value: <org UUID>
          - name: GREMLIN_ORG_SECRET
            value: <secret UUID>
          - name: GREMLIN_IDENTIFIER
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
